version: '3'
services:
  
  postgres:
    image: 'postgres:latest'
    # Postgres latest change config
    environment: 
      - POSTGRES_PASSWORD=postgres_password
  
  redis:
    image: 'redis:latest'

  nginx:
    depends_on: 
      - api
      - client
    # As it's a routing system, we want our Nginx to always restart if it fails
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    # port mapping, map our port 3050(or whatever) to port 80 in the container
    ports:
      - '3050:80'
  
  api:
    depends_on: 
      - postgres
    build:
      # in dockerfile, we only need to give the name of the file
      dockerfile: Dockerfile.dev
      # then we specify the root in context
      context: ./server
    volumes: 
      # just leave the node_module, no need to redirect to any folder
      - /app/node_modules
      # map the app folder, redirect it to our ./server folder
      # So if we have any changes in our ./server folder, it will automatically be mapped
      - ./server:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    # Recently, a bug was introduced with the latest Create React App version that is causing the React app to exit when starting with Docker Compose. 
    stdin_open: true
  
  worker:
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app

